feat: getAdvices helper created
AlanPinhon/advice-generator-app-ts pull request #1
Opened 2023-09-14 22:41 UTC by AlanPinhon

2023-09-15 21:24 UTC, gonzalo-novak requested changes
Sería bueno que indiques a nivel TS qué va a retornar el getAdvices y hacer el return del mismo vs a tener el console.log :D

2023-09-16 03:14 UTC, AlanPinhon commented
De acuerdo. Es que el console.log lo puse para verificar que haga la llamada de forma exitosa. ☝🤓

2023-09-16 05:01 UTC, gonzalo-novak requested changes

2023-09-16 05:01 UTC, gonzalo-novak commented on src/types/Advice.ts
Puedes poner lo que hay en el AdviceData.ts aquí. Ya que tiene relación con la misma entidad, en este caso Advice

2023-09-16 05:01 UTC, gonzalo-novak commented on src/types/AdviceData.ts
> +}
Tal vez el nombre del type podría ser algo como: AdviceResponseBody y hacer referencia del Advice en la propiedad slip:

```suggestion
export type AdviceResponseBody = {
  slip: Advice
}
```

Ese type podría estar en el Advice.ts

2023-09-16 05:01 UTC, gonzalo-novak commented on src/helpers/getAdvices.ts
> +  }
Podrías resumir el return con lo siguiente:

```suggestion
  return { ...data.slip }
```

2023-09-16 05:01 UTC, gonzalo-novak commented on src/helpers/getAdvices.ts
> +  const data:AdviceData = await response.json();
Si tomas el consejo de renombrar AdviceData a AdviceResponseBody tendrías que renombrarlo aquí también:

```suggestion
  const data: AdviceResponseBody = await response.json();
```

2023-09-16 05:01 UTC, gonzalo-novak commented on src/types/index.ts
> +export * from './AdviceData';
Si haces un export por cada type en su respectivo archivo, tal vez podrías omitir este archivo `/types/index.tsx`

2023-09-16 20:26 UTC, AlanPinhon commented on src/types/index.ts
> +export * from './AdviceData';
De acuerdo. Todos los cambios han sido realizados.

2023-09-18 03:17 UTC, gonzalo-novak approved these changes

2023-09-18 16:56 UTC, merged