test: tests in the AdviceGeneratorApp
AlanPinhon/advice-generator-app-ts pull request #5
Opened 2023-09-21 22:21 UTC by AlanPinhon

2023-09-21 23:12 UTC, gonzalo-novak requested changes

2023-09-21 23:12 UTC, gonzalo-novak commented on tests/components/AdviceGeneratorApp.spec.tsx
> +
Puedes revisar si el advice se ha pintado en la UI:

```suggestion
    expect(screen.getByText('Loading Advice...'))
    
    const adviceEl = await screen.findByText("Smile and the world smiles with you. Frown and you're on your own.");
    expect(adviceEl).toBeTruthy()
```

2023-09-21 23:12 UTC, gonzalo-novak commented on tests/components/AdviceGeneratorApp.spec.tsx
> +
Habría que hacer un caso en donde el API te responda un algún error 500. Veo que ese caso no está cachado en tu getAdvices.ts

```suggestion
  test("Should handle a failed response from the API", async () => {
    server.use(
      rest.get('https://api.adviceslip.com/advice', (_, res, ctx) => {
        return res(ctx.status(500), ctx.json({ ok: false, message: 'An error has ocurred' }))
      })
    )

    render(<AdviceGeneratorApp/>);
    const errorMsg = await screen.findByText('Network request failed');
    expect(errorMsg).toBeTruthy();
  })
```

El getAdvices no revisa si el response fue exitoso o no. Te puedes basar en el `response.ok` para saber eso:

```js
export const getAdvices = async (): Promise<Advice> => {
  const url = 'https://api.adviceslip.com/advice';

  const response = await fetch(url);
  const data:AdviceResponseBody = await response.json();  
  
  // Este es la condicional que se podría añadir:
  if(!response.ok) throw data; // Aquí se retorna el JSON que contiene el error. Este va a ser cachado por el try catch que está en el archivo useFetchAdvices.ts

  return { ...data.slip } // De no ser que haya un error a nivel API, entonces ya podemos retornar la respuesta exitosa
};
```

A final de cuentas no usaríamos dicho objeto de error porque desconocemos a nivel API cómo es la estructura del la respuesta de error que te retorna, pero lo que sí estamos verificando es que vamos a mostrar el mensaje "Network request failed" ya sea cuando el servidor haya retornado una respuesta con un status code diferente a 200-299 o haya algún problema de conexión en general.

2023-09-21 23:12 UTC, gonzalo-novak commented on tests/components/AdviceGeneratorApp.spec.tsx
> +    expect(errorMsg).toBeTruthy();
Veo que se repite la query dos veces para un mismo elemento:

```suggestion
    const errorMsg = await screen.findByText('Network request failed');
    expect(errorMsg).toBeTruthy();
```

2023-09-21 23:12 UTC, gonzalo-novak commented on src/mocks/handlers.ts
> +  }),
Este JSON lo puedes meter en un archivo que se llame `mocks/mock.advice.json` y lo puedes importar como un objeto en cada archivo que lo necesites. En plan:

```ts
import mockAdviceResponse from 'mocks/mock.advice.json'

ctx.json(mockAdviceResponse)
```

2023-09-22 01:43 UTC, AlanPinhon commented on tests/components/AdviceGeneratorApp.spec.tsx
> +
Había visto en algunos ejemplos en el que si la respuesta no fuese `ok`, lanzara el error. Entonces realizo ese ajuste para retornar el json del error.

2023-09-22 01:44 UTC, AlanPinhon commented on tests/components/AdviceGeneratorApp.spec.tsx
> +    expect(errorMsg).toBeTruthy();
Tienes razón. Añadí una línea de más. Lo tomo en cuenta para la refactorización.

2023-09-22 04:16 UTC, gonzalo-novak requested changes
Bien por el momento 🍰

2023-09-22 04:16 UTC, gonzalo-novak commented on tests/components/AdviceGeneratorApp.spec.tsx
> +    screen.debug();
Recuerda remover los `screen.debug()` cuando hayas terminado de validar tus tests 😃

2023-09-22 04:16 UTC, gonzalo-novak commented on tests/components/AdviceGeneratorApp.spec.tsx
> -        return res.networkError('Network request failed')
Sugiero que mantengas 2 tests, uno cuando hay un networkError y el otro cuando sí se hizo la conexión pero el server respondió con un status code diferente a 200-299 🦺

2023-09-22 04:42 UTC, AlanPinhon commented on tests/components/AdviceGeneratorApp.spec.tsx
> +    screen.debug();
Siempre se me olvida. Ya lo quito. 🤡

2023-09-22 04:43 UTC, AlanPinhon commented on tests/components/AdviceGeneratorApp.spec.tsx
> -        return res.networkError('Network request failed')
Vale, subo el último commit con esos cambios. 🛠

2023-09-22 04:51 UTC, gonzalo-novak approved these changes
¡Bien! 👏🏻

2023-09-22 17:37 UTC, merged