test: tests in AdviceErrorMsg component
AlanPinhon/advice-generator-app-ts pull request #7
Opened 2023-09-26 02:02 UTC by AlanPinhon

2023-09-26 03:08 UTC, gonzalo-novak commented on tests/components/AdviceErrorMsg.spec.tsx
> +    );
Como se está mandando el mock de `getTips` al componente, el `server.use` podría ser descartado puesto que en teoría no se está usando aquí 🤓

2023-09-26 03:08 UTC, gonzalo-novak commented on tests/components/AdviceErrorMsg.spec.tsx
> +  });
Creo que este test podría ser descartado debido que se hace lo mismo en el segundo test 😄

2023-09-26 04:34 UTC, AlanPinhon commented on tests/components/AdviceErrorMsg.spec.tsx
> +  });
Entendido. Esa parte será eliminada. 🤠

2023-09-26 23:38 UTC, gonzalo-novak requested changes

2023-09-26 23:38 UTC, gonzalo-novak commented on tests/components/AdviceErrorMsg.spec.tsx
> +const getTipsMock = vi.fn();
Creo que olvidaste colocar este mock dentro del primer test 😅

2023-09-27 00:35 UTC, AlanPinhon commented on tests/components/AdviceErrorMsg.spec.tsx
> +const getTipsMock = vi.fn();
Cierto. Perdón que se me hayan ido pequeñas cosas. Ya está todo ahora si (según yo). 🤡

2023-09-27 01:24 UTC, gonzalo-novak approved these changes
¡Vientos! 👏🏻 🎉

2023-09-27 01:26 UTC, merged